name: Check code quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          script/ci/linting.sh 2>&1 | tee code-quality-report.md

      - name: Upload analysis report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality-report
          path: code-quality-report.md
