name: Check code quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run linters
        run: |
          set +e  # Do not stop on errors
          
          ruff check . | tee ruff-report.md
          RUFF_EXIT=${PIPESTATUS[0]}
          
          pyright | tee pyright-report.md
          PYRIGHT_EXIT=${PIPESTATUS[0]}

          set -e # Bring back the stop on errors
          
          cat ruff-report.md pyright-report.md > report.md
          
          echo "Ruff exit code: $RUFF_EXIT"
          echo "Pyright exit code: $PYRIGHT_EXIT"
          
          if [ $RUFF_EXIT -ne 0 ] || [ $PYRIGHT_EXIT -ne 0 ]; then
            echo "::error::Linting failed"
            exit 1
          fi

      - name: Upload analysis report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality
          path: |
            ruff-report.md
            pyright-report.md
