name: Check code quality

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Ruff
        id: ruff
        continue-on-error: true
        run: ruff check . | tee ruff-report.md

      - name: Run Pyright  
        id: pyright
        continue-on-error: true
        run: pyright | tee pyright-report.md

      - name: Upload analysis report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-quality
          path: |
            ruff-report.md
            pyright-report.md

      - name: Fail if any linter failed
        if: steps.ruff.conclusion == 'failure' || steps.pyright.conclusion == 'failure'
        run: |
            echo "::error::One or more linters failed"
            exit 1
